<template>
    <MainLayout>
        <template #sidebar>
            <!-- Empty sidebar to hide it -->
        </template>
        
        <div class="max-w-8xl mx-auto py-10 mt-4 bg-white dark:bg-gray-800 rounded-xl shadow p-6">
            <h1 class="text-3xl font-bold mb-6 text-gray-900 dark:text-white">
                Terms of Service
            </h1>

            <p class="mb-4 text-gray-700 dark:text-gray-300">
                Welcome to ToolHub. By accessing and using this website, you accept
                and agree to be bound by the terms and conditions described below.
                If you do not agree with these terms, please do not use our website.
            </p>

            <h2 class="text-xl font-semibold mt-6 mb-2 text-gray-900 dark:text-white">
                Use of the Website
            </h2>

            <p class="mb-4 text-gray-700 dark:text-gray-300">
                ToolHub provides a collection of free online tools for developers
                and general users. You agree to use this website only for lawful
                purposes and in a way that does not harm the website or other users.
            </p>

            <h2 class="text-xl font-semibold mt-6 mb-2 text-gray-900 dark:text-white">
                No Warranty
            </h2>

            <p class="mb-4 text-gray-700 dark:text-gray-300">
                All tools and services provided on ToolHub are offered "as is"
                without any guarantees of accuracy, reliability, or availability.
                While we strive to provide useful tools, we do not guarantee that
                the results generated by these tools will always be correct.
            </p>

            <h2 class="text-xl font-semibold mt-6 mb-2 text-gray-900 dark:text-white">
                Limitation of Liability
            </h2>

            <p class="mb-4 text-gray-700 dark:text-gray-300">
                ToolHub shall not be held responsible for any direct or indirect
                damages resulting from the use or inability to use the tools
                provided on this website.
            </p>

            <h2 class="text-xl font-semibold mt-6 mb-2 text-gray-900 dark:text-white">
                Third-Party Services
            </h2>

            <p class="mb-4 text-gray-700 dark:text-gray-300">
                This website may use third-party services such as analytics or
                advertising networks. These services may collect certain data
                according to their own privacy policies.
            </p>

            <h2 class="text-xl font-semibold mt-6 mb-2 text-gray-900 dark:text-white">
                Intellectual Property
            </h2>

            <p class="mb-4 text-gray-700 dark:text-gray-300">
                All content on this website, including text, design, and tools,
                is the property of ToolHub unless otherwise stated. Unauthorized
                copying or redistribution is not permitted.
            </p>

            <h2 class="text-xl font-semibold mt-6 mb-2 text-gray-900 dark:text-white">
                Changes to the Terms
            </h2>

            <p class="mb-4 text-gray-700 dark:text-gray-300">
                We reserve the right to modify these Terms of Service at any time.
                Any updates will be posted on this page.
            </p>

            <h2 class="text-xl font-semibold mt-6 mb-2 text-gray-900 dark:text-white">
                Contact
            </h2>

            <p class="text-gray-700 dark:text-gray-300">
                If you have any questions about these Terms of Service, please
                contact us through our contact page.
            </p>
        </div>
    </MainLayout>
</template>

<script setup>
import MainLayout from "@/Layouts/MainLayout.vue";
</script>
